<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>

        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>link</TrimMode>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Concentus.Oggfile" Version="1.0.7" />
        <PackageReference Include="DisCatSharp.Voice.Natives" Version="10.7.0" />
        <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
        <PackageReference Include="FFmpeg.Loader" Version="3.0.2" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
        <PackageReference Include="NetCord" Version="1.0.0-alpha.490" />
        <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.490" />
        <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.490" />
        <PackageReference Include="NetCord.Services" Version="1.0.0-alpha.490" />
        <PackageReference Include="Sodium.Core" Version="1.4.1" />
        <PackageReference Include="YoutubeExplode" Version="6.6.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CobaltApi\CobaltApi.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Utilities\" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Singularity.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
